"""Approved public scholarship sources.

These pages are public discovery sources, not APIs.  Staff review a listing
before it is sent to the ingestion endpoint; the app never scrapes, bypasses
logins, or republishes a source's full catalogue.
"""

from typing import Any


SOURCE_CATALOG: list[dict[str, Any]] = [
    {
        "id": "university-of-arizona-scholarship-universe",
        "name": "University of Arizona Scholarship Universe",
        "kind": "university",
        "country": "US",
        "state": "AZ",
        "url": "https://financialaid.arizona.edu/ScholarshipUniverse",
        "import_method": "reviewed_manual",
        "notes": "The university provides a public scholarship view; verify each listing before importing.",
    },
    {
        "id": "kent-state-scholarship-universe",
        "name": "Kent State ScholarshipUniverse",
        "kind": "university",
        "country": "US",
        "url": "https://www.kent.edu/fbe-center/scholarship-universe",
        "import_method": "reviewed_manual",
        "notes": "Public listings are available; preserve the original scholarship and application links.",
    },
    {
        "id": "university-of-cincinnati-scholarships",
        "name": "University of Cincinnati Scholarships",
        "kind": "university",
        "country": "US",
        "url": "https://www.uc.edu/about/financial-aid/aid/scholarships/search.html",
        "import_method": "reviewed_manual",
        "notes": "Some awards are automatic based on admission; record that in eligibility or requirements.",
    },
    {
        "id": "community-foundation-locator",
        "name": "Council on Foundations Community Foundation Locator",
        "kind": "directory",
        "country": "US",
        "url": "https://cof.org/page/community-foundation-locator",
        "import_method": "discovery_only",
        "notes": "Use the locator to find a local foundation, then review and cite the foundation's own scholarship page.",
    },
    {
        "id": "college-scorecard",
        "name": "College Scorecard",
        "kind": "open_database",
        "country": "US",
        "url": "https://collegescorecard.ed.gov/data/",
        "import_method": "enrichment_only",
        "notes": "Free institution and financial-aid context; it is not a feed of individual scholarships.",
    },
    # Coverage batch 1: one official major-university source in each of the
    # ten most populous states. Additional universities will be added per state
    # before moving to the next coverage batch.
    {
        "id": "ucla-scholarships",
        "name": "UCLA Financial Aid & Scholarships",
        "kind": "university",
        "country": "US",
        "state": "CA",
        "url": "https://financialaid.ucla.edu/types-of-aid/scholarships",
        "import_method": "reviewed_manual",
        "notes": "Review scholarship details and application requirements on UCLA's official page before importing.",
    },
    {
        "id": "university-of-texas-at-austin-scholarships",
        "name": "University of Texas at Austin Scholarships",
        "kind": "university",
        "country": "US",
        "state": "TX",
        "url": "https://onestop.utexas.edu/managing-costs/scholarships-financial-aid/types-of-financial-aid/scholarships/",
        "import_method": "reviewed_manual",
        "notes": "Use the official LASSO scholarship finder and preserve the originating scholarship link.",
    },
    {
        "id": "university-of-florida-scholarships",
        "name": "University of Florida Scholarships",
        "kind": "university",
        "country": "US",
        "state": "FL",
        "url": "https://www.sfa.ufl.edu/types-of-aid/scholarships/",
        "import_method": "reviewed_manual",
        "notes": "Verify award availability, residency requirements, and deadlines on the official page.",
    },
    {
        "id": "new-york-university-financial-aid",
        "name": "New York University Scholarships and Grants",
        "kind": "university",
        "country": "US",
        "state": "NY",
        "url": "https://bulletins.nyu.edu/undergraduate/liberal-studies/cost-attendance/financial-aid/",
        "import_method": "reviewed_manual",
        "notes": "Confirm eligibility and whether the admissions application is the scholarship application.",
    },
    {
        "id": "penn-state-scholarships",
        "name": "Penn State Scholarships",
        "kind": "university",
        "country": "US",
        "state": "PA",
        "url": "https://studentaid.psu.edu/types-of-aid/scholarships",
        "import_method": "reviewed_manual",
        "notes": "Use Penn State's official student-aid information to verify every award before import.",
    },
    {
        "id": "university-of-illinois-scholarships",
        "name": "University of Illinois Urbana-Champaign Scholarships",
        "kind": "university",
        "country": "US",
        "state": "IL",
        "url": "https://www.osfa.illinois.edu/types-of-aid/scholarships/",
        "import_method": "reviewed_manual",
        "notes": "Separate university, federal/state, and outside awards when recording eligibility.",
    },
    {
        "id": "ohio-state-financial-aid",
        "name": "The Ohio State University Scholarships",
        "kind": "university",
        "country": "US",
        "state": "OH",
        "url": "https://undergrad.osu.edu/cost-and-aid/financial-aid",
        "import_method": "reviewed_manual",
        "notes": "Verify Scholarship Universe requirements and application deadlines before import.",
    },
    {
        "id": "georgia-tech-scholarships",
        "name": "Georgia Tech Scholarships",
        "kind": "university",
        "country": "US",
        "state": "GA",
        "url": "https://finaid.gatech.edu/undergraduate-types-aid/scholarships/",
        "import_method": "reviewed_manual",
        "notes": "Record residency rules separately for state programs such as HOPE and Zell Miller.",
    },
    {
        "id": "university-of-north-carolina-scholarships",
        "name": "University of North Carolina at Chapel Hill Scholarships",
        "kind": "university",
        "country": "US",
        "state": "NC",
        "url": "https://studentaid.unc.edu/types/scholarships/",
        "import_method": "reviewed_manual",
        "notes": "Verify the current scholarship application and criteria on the official page before import.",
    },
    {
        "id": "university-of-michigan-lsa-scholarships",
        "name": "University of Michigan LSA Scholarships",
        "kind": "university",
        "country": "US",
        "state": "MI",
        "url": "https://lsa.umich.edu/lsa/prospective-students/undergraduate/scholarships-financialaid-tuition.html",
        "import_method": "reviewed_manual",
        "notes": "Verify college-specific and university-wide award eligibility before importing.",
    },
    # Coverage batch 2: the next ten states by population.
    {
        "id": "rutgers-scholarships",
        "name": "Rutgers University Scholarships",
        "kind": "university",
        "country": "US",
        "state": "NJ",
        "url": "https://admissions.rutgers.edu/costs-and-aid/scholarships",
        "import_method": "reviewed_manual",
        "notes": "Verify campus, residency, and renewal requirements for each Rutgers award.",
    },
    {
        "id": "university-of-virginia-scholarships-grants",
        "name": "University of Virginia Scholarships and Grants",
        "kind": "university",
        "country": "US",
        "state": "VA",
        "url": "https://sfs.virginia.edu/financial-aid-current-students/current-undergraduate-students/financial-aid-basics/types-aid/scholarships-grants",
        "import_method": "reviewed_manual",
        "notes": "Record need-based requirements and distinguish AccessUVA grants from named scholarships.",
    },
    {
        "id": "university-of-washington-scholarships",
        "name": "University of Washington Scholarships",
        "kind": "university",
        "country": "US",
        "state": "WA",
        "url": "https://admit.washington.edu/costs/scholarships/",
        "import_method": "reviewed_manual",
        "notes": "Verify Washington-residency and admission-application requirements before import.",
    },
    {
        "id": "university-of-tennessee-knoxville-scholarships",
        "name": "University of Tennessee, Knoxville Scholarships",
        "kind": "university",
        "country": "US",
        "state": "TN",
        "url": "https://admissions.utk.edu/costs-scholarships-aid/",
        "import_method": "reviewed_manual",
        "notes": "Verify whether awards are automatic, competitive, or college-specific before import.",
    },
    {
        "id": "umass-amherst-scholarships",
        "name": "University of Massachusetts Amherst Scholarships",
        "kind": "university",
        "country": "US",
        "state": "MA",
        "url": "https://www.umass.edu/financialaid/umass-amherst-scholarship-faq",
        "import_method": "reviewed_manual",
        "notes": "Verify the AcademicWorks opportunity, deadline, and school or college requirements.",
    },
    {
        "id": "indiana-university-scholarships",
        "name": "Indiana University Scholarships",
        "kind": "university",
        "country": "US",
        "state": "IN",
        "url": "https://scholarships.indiana.edu/",
        "import_method": "reviewed_manual",
        "notes": "Review campus and program eligibility on Indiana University's official scholarship site.",
    },
    {
        "id": "university-of-maryland-scholarship-search",
        "name": "University of Maryland Scholarship Search",
        "kind": "university",
        "country": "US",
        "state": "MD",
        "url": "https://financialaid.umd.edu/resources-policies/scholarship-search",
        "import_method": "reviewed_manual",
        "notes": "Use the official Scholarship Universe information and retain the originating award page.",
    },
    {
        "id": "university-of-missouri-scholarships",
        "name": "University of Missouri Scholarships",
        "kind": "university",
        "country": "US",
        "state": "MO",
        "url": "https://financialaid.missouri.edu/types-of-aid/scholarships/",
        "import_method": "reviewed_manual",
        "notes": "Verify scholarship terms and incoming, transfer, or continuing-student eligibility.",
    },
    {
        "id": "university-of-wisconsin-madison-scholarships",
        "name": "University of Wisconsin-Madison Scholarships",
        "kind": "university",
        "country": "US",
        "state": "WI",
        "url": "https://awards.advising.wisc.edu/",
        "import_method": "reviewed_manual",
        "notes": "Verify campuswide or nationally competitive scholarship requirements before import.",
    },
    # Coverage batch 3: the next ten states by population.
    {
        "id": "university-of-colorado-boulder-scholarships",
        "name": "University of Colorado Boulder Scholarships",
        "kind": "university",
        "country": "US",
        "state": "CO",
        "url": "https://www.colorado.edu/scholarships/cuboulder-scholarship-app",
        "import_method": "reviewed_manual",
        "notes": "Verify each CU Boulder Scholarship Application opportunity, deadline, and eligibility before import.",
    },
    {
        "id": "university-of-minnesota-scholarships",
        "name": "University of Minnesota Scholarships",
        "kind": "university",
        "country": "US",
        "state": "MN",
        "url": "https://onestop.umn.edu/finances/types-financial-aid/scholarships",
        "import_method": "reviewed_manual",
        "notes": "Verify campus, academic-profile, and financial-need requirements before import.",
    },
    {
        "id": "university-of-south-carolina-scholarships",
        "name": "University of South Carolina Scholarships",
        "kind": "university",
        "country": "US",
        "state": "SC",
        "url": "https://www.sc.edu/about/offices_and_divisions/undergraduate_admissions/tuition_scholarships/index.php",
        "import_method": "reviewed_manual",
        "notes": "Separate resident, nonresident, and departmental scholarship eligibility.",
    },
    {
        "id": "university-of-alabama-scholarships",
        "name": "University of Alabama Scholarships",
        "kind": "university",
        "country": "US",
        "state": "AL",
        "url": "https://scholarships.ua.edu/",
        "import_method": "reviewed_manual",
        "notes": "Verify the award type, eligibility, and renewal conditions on the official scholarship site.",
    },
    {
        "id": "louisiana-state-university-scholarships",
        "name": "Louisiana State University Scholarships",
        "kind": "university",
        "country": "US",
        "state": "LA",
        "url": "https://www.lsu.edu/financialaid/scholarships/incoming-students.php",
        "import_method": "reviewed_manual",
        "notes": "Confirm applicant type, residency, and admission-application timing before import.",
    },
    {
        "id": "university-of-kentucky-academic-scholarships",
        "name": "University of Kentucky Academic Scholarships",
        "kind": "university",
        "country": "US",
        "state": "KY",
        "url": "https://studentsuccess.uky.edu/financial-aid-and-scholarships/academic-scholarships",
        "import_method": "reviewed_manual",
        "notes": "Verify incoming, transfer, current, and international student eligibility separately.",
    },
    {
        "id": "university-of-oregon-scholarships",
        "name": "University of Oregon Scholarships",
        "kind": "university",
        "country": "US",
        "state": "OR",
        "url": "https://financialaid.uoregon.edu/scholarships",
        "import_method": "reviewed_manual",
        "notes": "Review university and external scholarship requirements before importing a listing.",
    },
    {
        "id": "university-of-oklahoma-scholarships",
        "name": "University of Oklahoma Scholarships",
        "kind": "university",
        "country": "US",
        "state": "OK",
        "url": "https://www.ou.edu/admissions/affordability/scholarships",
        "import_method": "reviewed_manual",
        "notes": "Verify scholarship criteria and the student's admission status before import.",
    },
    {
        "id": "university-of-connecticut-scholarships",
        "name": "University of Connecticut Scholarships",
        "kind": "university",
        "country": "US",
        "state": "CT",
        "url": "https://financialaid.uconn.edu/scholarships/",
        "import_method": "reviewed_manual",
        "notes": "Verify departmental, merit, state, or external-scholarship status before import.",
    },
    {
        "id": "university-of-utah-scholarships",
        "name": "University of Utah Scholarships",
        "kind": "university",
        "country": "US",
        "state": "UT",
        "url": "https://financialaid.utah.edu/types-of-aid/scholarships/index.php",
        "import_method": "reviewed_manual",
        "notes": "Verify entering, transfer, current-student, and college-level eligibility before import.",
    },
    # Coverage batch 4: the next ten states by population.
    {
        "id": "iowa-state-university-scholarships",
        "name": "Iowa State University Scholarships",
        "kind": "university",
        "country": "US",
        "state": "IA",
        "url": "https://www.iastate.edu/admission-and-aid/affording-college/scholarships",
        "import_method": "reviewed_manual",
        "notes": "Verify automatic, OneApp, transfer, and international scholarship requirements before import.",
    },
    {
        "id": "university-of-nevada-las-vegas-scholarships",
        "name": "University of Nevada, Las Vegas Scholarships",
        "kind": "university",
        "country": "US",
        "state": "NV",
        "url": "https://www.unlv.edu/admissions/paying-for-college",
        "import_method": "reviewed_manual",
        "notes": "Verify admission, residency, and financial-aid application requirements before import.",
    },
    {
        "id": "university-of-arkansas-scholarships",
        "name": "University of Arkansas Scholarships",
        "kind": "university",
        "country": "US",
        "state": "AR",
        "url": "https://scholarships.uark.edu/",
        "import_method": "reviewed_manual",
        "notes": "Use the Academic Scholarship Office details to verify priority dates and eligibility.",
    },
    {
        "id": "university-of-mississippi-scholarships",
        "name": "University of Mississippi Scholarships",
        "kind": "university",
        "country": "US",
        "state": "MS",
        "url": "https://olemiss.edu/finaid/types-of-aid/scholarships/",
        "import_method": "reviewed_manual",
        "notes": "Verify current academic year, residency, and incoming-student scholarship criteria.",
    },
    {
        "id": "university-of-kansas-scholarships",
        "name": "University of Kansas Scholarships",
        "kind": "university",
        "country": "US",
        "state": "KS",
        "url": "https://affordability.ku.edu/scholarships",
        "import_method": "reviewed_manual",
        "notes": "Verify admission, residency, and college or departmental scholarship eligibility before import.",
    },
    {
        "id": "university-of-new-mexico-scholarships",
        "name": "University of New Mexico Scholarships",
        "kind": "university",
        "country": "US",
        "state": "NM",
        "url": "https://scholarships.unm.edu/",
        "import_method": "reviewed_manual",
        "notes": "Verify resident, nonresident, lottery, tribal, and general scholarship requirements.",
    },
    {
        "id": "university-of-nebraska-lincoln-scholarships",
        "name": "University of Nebraska-Lincoln Scholarships",
        "kind": "university",
        "country": "US",
        "state": "NE",
        "url": "https://financialaid.unl.edu/apply-funds/",
        "import_method": "reviewed_manual",
        "notes": "Verify automatic consideration and scholarship-specific application requirements before import.",
    },
    {
        "id": "university-of-idaho-scholarships",
        "name": "University of Idaho Scholarships",
        "kind": "university",
        "country": "US",
        "state": "ID",
        "url": "https://www.uidaho.edu/financial-aid/scholarships",
        "import_method": "reviewed_manual",
        "notes": "Verify resident, out-of-state, international, and National Merit award rules before import.",
    },
    {
        "id": "west-virginia-university-scholarships",
        "name": "West Virginia University Scholarships",
        "kind": "university",
        "country": "US",
        "state": "WV",
        "url": "https://www.static.wvu.edu/admissions/undergraduate/cost-and-aid/scholarships/first-time-freshmen/",
        "import_method": "reviewed_manual",
        "notes": "Verify merit, need, leadership, residency, and admission requirements before import.",
    },
    {
        "id": "university-of-hawaii-manoa-scholarships",
        "name": "University of Hawaiʻi at Mānoa Scholarships",
        "kind": "university",
        "country": "US",
        "state": "HI",
        "url": "https://manoa.hawaii.edu/fas/types-of-aid/scholarships/",
        "import_method": "reviewed_manual",
        "notes": "Verify university, system, departmental, local, and international scholarship eligibility before import.",
    },
    # Coverage batch 5: final state coverage.
    {
        "id": "university-of-new-hampshire-scholarships",
        "name": "University of New Hampshire Scholarships",
        "kind": "university",
        "country": "US",
        "state": "NH",
        "url": "https://www.unh.edu/financialaid/types-aid/scholarships",
        "import_method": "reviewed_manual",
        "notes": "Verify merit, departmental, residency, and renewal requirements before import.",
    },
    {
        "id": "university-of-maine-scholarships",
        "name": "University of Maine Scholarships",
        "kind": "university",
        "country": "US",
        "state": "ME",
        "url": "https://umaine.edu/admissions/cost-aid/merit-scholarships/",
        "import_method": "reviewed_manual",
        "notes": "Verify first-year, transfer, residency, and application-deadline requirements before import.",
    },
    {
        "id": "university-of-montana-scholarships",
        "name": "University of Montana Scholarships",
        "kind": "university",
        "country": "US",
        "state": "MT",
        "url": "https://www.umt.edu/student-financial-services/financial-aid/scholarships/apply-for-scholarships.php",
        "import_method": "reviewed_manual",
        "notes": "Verify current opportunity details and annual Scholarship Universe deadlines before import.",
    },
    {
        "id": "university-of-rhode-island-scholarships",
        "name": "University of Rhode Island Scholarships",
        "kind": "university",
        "country": "US",
        "state": "RI",
        "url": "https://web.uri.edu/admission/scholarships/",
        "import_method": "reviewed_manual",
        "notes": "Verify merit, honors, and application-completion requirements before import.",
    },
    {
        "id": "university-of-delaware-scholarships",
        "name": "University of Delaware Scholarships",
        "kind": "university",
        "country": "US",
        "state": "DE",
        "url": "https://www.udel.edu/students/student-financial-services/undergraduate/",
        "import_method": "reviewed_manual",
        "notes": "Verify automatic merit consideration and continuing-student scholarship requirements before import.",
    },
    {
        "id": "south-dakota-state-university-scholarships",
        "name": "South Dakota State University Scholarships",
        "kind": "university",
        "country": "US",
        "state": "SD",
        "url": "https://www.sdstate.edu/admissions/paying/academic-scholarships",
        "import_method": "reviewed_manual",
        "notes": "Verify first-time, transfer, graduate, departmental, and portal application details before import.",
    },
    {
        "id": "north-dakota-state-university-scholarships",
        "name": "North Dakota State University Scholarships",
        "kind": "university",
        "country": "US",
        "state": "ND",
        "url": "https://www.ndsu.edu/onestop/scholarships-grants-and-tuition-waivers",
        "import_method": "reviewed_manual",
        "notes": "Verify institutional, state, tribal, and tuition-waiver eligibility before import.",
    },
    {
        "id": "university-of-alaska-anchorage-scholarships",
        "name": "University of Alaska Anchorage Scholarships",
        "kind": "university",
        "country": "US",
        "state": "AK",
        "url": "https://www.uaa.alaska.edu/students/financial-aid/types-of-aid/scholarships/index",
        "import_method": "reviewed_manual",
        "notes": "Verify UA Foundation, state, Alaska-residency, and scholarship-specific requirements before import.",
    },
    {
        "id": "university-of-vermont-scholarships",
        "name": "University of Vermont Scholarships",
        "kind": "university",
        "country": "US",
        "state": "VT",
        "url": "https://www.uvm.edu/studentfinancialservices/scholarships",
        "import_method": "reviewed_manual",
        "notes": "Verify prospective-student, Vermont-resident, and outside-scholarship requirements before import.",
    },
    {
        "id": "university-of-wyoming-scholarships",
        "name": "University of Wyoming Scholarships",
        "kind": "university",
        "country": "US",
        "state": "WY",
        "url": "https://www.uwyo.edu/sfa/",
        "import_method": "reviewed_manual",
        "notes": "Verify merit, need-based, resident, and scholarship-specific eligibility before import.",
    },
]


def list_sources() -> list[dict[str, Any]]:
    """Return a copy so callers cannot alter the approved source catalogue."""

    return [dict(source) for source in SOURCE_CATALOG]
